import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${inter.className} bg-[#F0EEED]`}
          suppressHydrationWarning={true}
        >
          <main className="main">
            <Nav />
            {children}
          </main>
        </body>
      </Provider>
    </html>
  );
}
